// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AddOwnerController from "./add_owner_controller"
application.register("add-owner", AddOwnerController)

import AddressAutocompleteController from "./address_autocomplete_controller"
application.register("address-autocomplete", AddressAutocompleteController)

import BedCopyController from "./bed_copy_controller"
application.register("bed-copy", BedCopyController)

import BookingConditionsController from "./booking_conditions_controller"
application.register("booking-conditions", BookingConditionsController)

import CheckboxController from "./checkbox_controller"
application.register("checkbox", CheckboxController)

import CollapsibleController from "./collapsible_controller"
application.register("collapsible", CollapsibleController)

import EarningCalculatorController from "./earning_calculator_controller"
application.register("earning-calculator", EarningCalculatorController)

import FetchEarningsController from "./fetch_earnings_controller"
application.register("fetch-earnings", FetchEarningsController)

import FilterController from "./filter_controller"
application.register("filter", FilterController)

import FlatpickrTurboController from "./flatpickr_turbo_controller"
application.register("flatpickr-turbo", FlatpickrTurboController)

import IframeController from "./iframe_controller"
application.register("iframe", IframeController)

import ImportBookingsController from "./import_bookings_controller"
application.register("import-bookings", ImportBookingsController)

import MapController from "./map_controller"
application.register("map", MapController)

import PasswordToggleController from "./password_toggle_controller"
application.register("password-toggle", PasswordToggleController)

import PdfModalController from "./pdf_modal_controller"
application.register("pdf-modal", PdfModalController)

import PricingController from "./pricing_controller"
application.register("pricing", PricingController)

import SearchBarController from "./search_bar_controller"
application.register("search-bar", SearchBarController)

import SearchController from "./search_controller"
application.register("search", SearchController)

import SearchPropertiesController from "./search_properties_controller"
application.register("search-properties", SearchPropertiesController)

import SignatureCaptureController from "./signature_capture_controller"
application.register("signature-capture", SignatureCaptureController)

import SortableController from "./sortable_controller"
application.register("sortable", SortableController)

import SpinnerBtnController from "./spinner_btn_controller"
application.register("spinner-btn", SpinnerBtnController)

import SpinnerPdfController from "./spinner_pdf_controller"
application.register("spinner-pdf", SpinnerPdfController)

import ToggleFeaturedController from "./toggle_featured_controller"
application.register("toggle-featured", ToggleFeaturedController)

import TypedJsController from "./typed_js_controller"
application.register("typed-js", TypedJsController)

import UnavailableDatesController from "./unavailable_dates_controller"
application.register("unavailable-dates", UnavailableDatesController)

import UpdateFieldController from "./update_field_controller"
application.register("update-field", UpdateFieldController)
