// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application";

import CallFlatpickrController from "./call_flatpickr_controller";
application.register("call-flatpickr", CallFlatpickrController);

import EditTaskController from "./edit_task_controller";
application.register("edit-task", EditTaskController);

import HelloController from "./hello_controller";
application.register("hello", HelloController);

import PasswordToggleController from "./password_toggle_controller";
application.register("password-toggle", PasswordToggleController);

import RateComponentController from "./rate_component_controller";
application.register("rate-component", RateComponentController);

import SidebarController from "./sidebar_controller";
application.register("sidebar", SidebarController);
