update_availability:
  cron: "0 6 * * *"
  class: "UpdateAvailabilityJob"
  active_job: true
  description: "Update availability from beds24 every morning at 6 am"
get_posts:
  cron: "0 0 * * *"
  class: "GetPostsJob"
  active_job: true
  description: "Get posts from the feed urls every day at midnight"
update_bookings:
  cron: "0 4 * * *"
  class: "UpdateBookingsJob"
  active_job: true
  description: "Update all the bookings from beds24 every morning at 4 am"
